import type { Conversation, Message, Contact } from "@/types/chat";

const now = Date.now();
const minute = 60 * 1000;
const hour = 60 * minute;

export const currentUserId = "user_me";

export const contacts: Contact[] = [
  {
    id: "user_sarah",
    name: "Sarah Al-Rashid",
    isOnline: true,
    role: "City Planner",
    department: "Urban Development",
  },
  {
    id: "user_omar",
    name: "Omar Khalid",
    isOnline: true,
    role: "Transport Engineer",
    department: "Mobility & Transit",
  },
  {
    id: "user_fatima",
    name: "Fatima Noor",
    isOnline: false,
    role: "Environmental Analyst",
    department: "Sustainability",
  },
  {
    id: "user_ahmed",
    name: "Ahmed Mansour",
    isOnline: true,
    role: "Infrastructure Lead",
    department: "Smart Infrastructure",
  },
  {
    id: "user_lina",
    name: "Lina Al-Sayed",
    isOnline: false,
    role: "Data Scientist",
    department: "City Intelligence",
  },
  {
    id: "user_yusuf",
    name: "Yusuf Ibrahim",
    isOnline: true,
    role: "Security Analyst",
    department: "Public Safety",
  },
];

export const seedConversations: Conversation[] = [
  {
    id: "conv_1",
    name: "Sarah Al-Rashid",
    isGroup: false,
    participants: [currentUserId, "user_sarah"],
    unreadCount: 2,
    isPinned: true,
    isOnline: true,
    subtitle: "City Planner",
    lastMessage: {
      id: "msg_s1",
      conversationId: "conv_1",
      senderId: "user_sarah",
      text: "The new district zoning plan is ready for review. Can we discuss it tomorrow?",
      timestamp: now - 5 * minute,
      status: "delivered",
    },
  },
  {
    id: "conv_2",
    name: "Metro Line Expansion",
    isGroup: true,
    participants: [currentUserId, "user_omar", "user_ahmed", "user_sarah"],
    unreadCount: 5,
    isPinned: true,
    isOnline: true,
    subtitle: "Omar, Ahmed, Sarah",
    lastMessage: {
      id: "msg_m1",
      conversationId: "conv_2",
      senderId: "user_omar",
      text: "Phase 2 station designs are finalized. Sending the updated route map now.",
      timestamp: now - 22 * minute,
      status: "delivered",
    },
  },
  {
    id: "conv_3",
    name: "Omar Khalid",
    isGroup: false,
    participants: [currentUserId, "user_omar"],
    unreadCount: 0,
    isPinned: false,
    isOnline: true,
    subtitle: "Transport Engineer",
    lastMessage: {
      id: "msg_o1",
      conversationId: "conv_3",
      senderId: currentUserId,
      text: "Thanks for the traffic flow analysis report!",
      timestamp: now - 2 * hour,
      status: "read",
    },
  },
  {
    id: "conv_4",
    name: "Fatima Noor",
    isGroup: false,
    participants: [currentUserId, "user_fatima"],
    unreadCount: 0,
    isPinned: false,
    isOnline: false,
    subtitle: "Environmental Analyst",
    lastMessage: {
      id: "msg_f1",
      conversationId: "conv_4",
      senderId: "user_fatima",
      text: "Air quality readings for Q3 are looking much better compared to last year.",
      timestamp: now - 5 * hour,
      status: "read",
    },
  },
  {
    id: "conv_5",
    name: "Smart Grid Team",
    isGroup: true,
    participants: [currentUserId, "user_ahmed", "user_lina"],
    unreadCount: 1,
    isPinned: false,
    isOnline: false,
    subtitle: "Ahmed, Lina",
    lastMessage: {
      id: "msg_sg1",
      conversationId: "conv_5",
      senderId: "user_ahmed",
      text: "Power distribution optimization algorithm is showing a 12% efficiency gain!",
      timestamp: now - 8 * hour,
      status: "delivered",
    },
  },
  {
    id: "conv_6",
    name: "Yusuf Ibrahim",
    isGroup: false,
    participants: [currentUserId, "user_yusuf"],
    unreadCount: 0,
    isPinned: false,
    isOnline: true,
    subtitle: "Security Analyst",
    lastMessage: {
      id: "msg_y1",
      conversationId: "conv_6",
      senderId: currentUserId,
      text: "Surveillance system upgrade is scheduled for next week.",
      timestamp: now - 1 * 24 * hour,
      status: "read",
    },
  },
];

export const seedMessages: Record<string, Message[]> = {
  conv_1: [
    {
      id: "msg_s_1",
      conversationId: "conv_1",
      senderId: currentUserId,
      text: "Hi Sarah, how's the zoning review coming along?",
      timestamp: now - 3 * hour,
      status: "read",
    },
    {
      id: "msg_s_2",
      conversationId: "conv_1",
      senderId: "user_sarah",
      text: "Making great progress! The residential zones are looking solid. Just need to finalize the commercial corridors.",
      timestamp: now - 2.5 * hour,
      status: "read",
    },
    {
      id: "msg_s_3",
      conversationId: "conv_1",
      senderId: currentUserId,
      text: "Perfect. Let me know when it's ready for the committee review.",
      timestamp: now - 2 * hour,
      status: "read",
    },
    {
      id: "msg_s_4",
      conversationId: "conv_1",
      senderId: "user_sarah",
      text: "Will do! I've also included the green space allocation recommendations.",
      timestamp: now - 1.5 * hour,
      status: "read",
    },
    {
      id: "msg_s_5",
      conversationId: "conv_1",
      senderId: "user_sarah",
      text: "The new district zoning plan is ready for review. Can we discuss it tomorrow?",
      timestamp: now - 5 * minute,
      status: "delivered",
    },
  ],
  conv_2: [
    {
      id: "msg_m_1",
      conversationId: "conv_2",
      senderId: "user_ahmed",
      text: "Team, we need to finalize the Phase 2 station locations by Friday.",
      timestamp: now - 4 * hour,
      status: "read",
    },
    {
      id: "msg_m_2",
      conversationId: "conv_2",
      senderId: "user_sarah",
      text: "I've overlaid the station proposals with population density data. Some interesting insights.",
      timestamp: now - 3.5 * hour,
      status: "read",
    },
    {
      id: "msg_m_3",
      conversationId: "conv_2",
      senderId: currentUserId,
      text: "Great work Sarah. Omar, how's the ridership projection looking?",
      timestamp: now - 3 * hour,
      status: "read",
    },
    {
      id: "msg_m_4",
      conversationId: "conv_2",
      senderId: "user_omar",
      text: "Projections indicate 45k daily riders on the new line. That's exceeding our initial estimate by 15%.",
      timestamp: now - 1 * hour,
      status: "read",
    },
    {
      id: "msg_m_5",
      conversationId: "conv_2",
      senderId: "user_omar",
      text: "Phase 2 station designs are finalized. Sending the updated route map now.",
      timestamp: now - 22 * minute,
      status: "delivered",
    },
  ],
  conv_3: [
    {
      id: "msg_o_1",
      conversationId: "conv_3",
      senderId: "user_omar",
      text: "Hey, I just finished the traffic flow analysis for downtown.",
      timestamp: now - 5 * hour,
      status: "read",
    },
    {
      id: "msg_o_2",
      conversationId: "conv_3",
      senderId: currentUserId,
      text: "That was quick! What did you find?",
      timestamp: now - 4.5 * hour,
      status: "read",
    },
    {
      id: "msg_o_3",
      conversationId: "conv_3",
      senderId: "user_omar",
      text: "Main bottleneck is at the Al-Khalid intersection. We could reduce congestion by 30% with a smart signal system.",
      timestamp: now - 4 * hour,
      status: "read",
    },
    {
      id: "msg_o_4",
      conversationId: "conv_3",
      senderId: currentUserId,
      text: "Thanks for the traffic flow analysis report!",
      timestamp: now - 2 * hour,
      status: "read",
    },
  ],
  conv_4: [
    {
      id: "msg_f_1",
      conversationId: "conv_4",
      senderId: "user_fatima",
      text: "I've compiled the environmental impact data for the new housing development.",
      timestamp: now - 24 * hour,
      status: "read",
    },
    {
      id: "msg_f_2",
      conversationId: "conv_4",
      senderId: currentUserId,
      text: "Thanks Fatima. Any concerns we should address?",
      timestamp: now - 22 * hour,
      status: "read",
    },
    {
      id: "msg_f_3",
      conversationId: "conv_4",
      senderId: "user_fatima",
      text: "Air quality readings for Q3 are looking much better compared to last year.",
      timestamp: now - 5 * hour,
      status: "read",
    },
  ],
  conv_5: [
    {
      id: "msg_sg_1",
      conversationId: "conv_5",
      senderId: "user_lina",
      text: "I've been running ML models on the power consumption data. Some fascinating patterns.",
      timestamp: now - 12 * hour,
      status: "read",
    },
    {
      id: "msg_sg_2",
      conversationId: "conv_5",
      senderId: currentUserId,
      text: "Interesting! What kind of patterns?",
      timestamp: now - 10 * hour,
      status: "read",
    },
    {
      id: "msg_sg_3",
      conversationId: "conv_5",
      senderId: "user_ahmed",
      text: "Power distribution optimization algorithm is showing a 12% efficiency gain!",
      timestamp: now - 8 * hour,
      status: "delivered",
    },
  ],
  conv_6: [
    {
      id: "msg_y_1",
      conversationId: "conv_6",
      senderId: "user_yusuf",
      text: "The new surveillance coverage analysis is complete. We have 94% coverage in public areas.",
      timestamp: now - 48 * hour,
      status: "read",
    },
    {
      id: "msg_y_2",
      conversationId: "conv_6",
      senderId: currentUserId,
      text: "Surveillance system upgrade is scheduled for next week.",
      timestamp: now - 24 * hour,
      status: "read",
    },
  ],
};
